
title: Ghatstays
description: Your guide through the mesmerising landscape of the western ghats.
url: https://ghatstays.com
email: ghatstays@gmail.com
instagram: https://www.instagram.com/ghatstays 
linkedin: https://in.linkedin.com/in/ghat-stays 
twitter: https://twitter.com/GhatStays 
justdial: https://jsdl.in/DT-99BTDKH6VI9    
facebook: https://m.facebook.com/profile.php?id=100085038775426&mibextid=ZbWKwL 
youtube: https://youtube.com/@ghatstays?si=Ke6yJfcNkgg84Hos 

logo: /assets/img/logos/Logo-v2-full-clr.png
logo-white: /assets/img/logos/logo-v2-full-white.png
logo-black: /assets/img/logos/Logo-v2-full-blk.png

sass:
  sass_dir: /assets/css/_sass/
  style: compressed

include:
  - _pages

collections_dir: site_collections

collections:
  stays:
    output: true

defaults:
  - scope:
      path: "properties/*"
    values:
      image: true

#compress.html
compress_html:
  clippings: [html, head, meta, title, link, body, div, script, header, footer]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []


plugins:
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-last-modified-at